### PR TITLE
Add ability about loading libraries.json to this library

### PR DESCRIPTION
**Pull request by SNWCreations**
See Minecrell/plugin-yml#54

Really useful when working with that Gradle plugin.

### CODE REVIEW

**Comment by frengor** [comment]
We already have such functionality in the `gradle` branch: https://github.com/AlessioDP/libby/blob/877bdfb2322d1911f43108906cce8d0163425af3/core/src/main/java/com/alessiodp/libby/LibraryManager.java#L749

[Example of JSON configuration](https://github.com/AlessioDP/libby/blob/gradle/core/src/test/resources/libby.json)

**Comment by SNWCreations** [comment]
> We already have such functionality in the `gradle` branch:
> 
> https://github.com/AlessioDP/libby/blob/877bdfb2322d1911f43108906cce8d0163425af3/core/src/main/java/com/alessiodp/libby/LibraryManager.java#L749
> 
> [Example of JSON configuration](https://github.com/AlessioDP/libby/blob/gradle/core/src/test/resources/libby.json)

Sorry for lossing the research on this and thank you for your reply. IDK how to let plugin-yml generate such json. :/ Any ideas?
Will the base branch of this PR still supported after v2 release? I'm focus on the stability.

**Comment by frengor** [comment]
> IDK how to let plugin-yml generate such json. :/ Any ideas?

I would make a PR to [Minecrell/plugin-yml](https://github.com/Minecrell/plugin-yml) and make it generate a Libby compatible JSON. Another option is to read the [Minecrell/plugin-yml](https://github.com/Minecrell/plugin-yml)'s JSON manually and load the libraries using Libby.

> Will the base branch of this PR still supported after v2 release? I'm focus on the stability.

No, only the 2.x.x will be supported, since it will become the stable version.

**Comment by SNWCreations** [comment]
> > IDK how to let plugin-yml generate such json. :/ Any ideas?
> 
> I would make a PR to [Minecrell/plugin-yml](https://github.com/Minecrell/plugin-yml) and make it generate a Libby compatible JSON. Another option is to read the [Minecrell/plugin-yml](https://github.com/Minecrell/plugin-yml)'s JSON manually and load the libraries using Libby.
> 
> > Will the base branch of this PR still supported after v2 release? I'm focus on the stability.
> 
> No, only the 2.x.x will be supported, since it will become the stable version.

Okay. Thanks for your reply. Looking forward to the v2 release.

Addition: Minecrell projects rarely updates, IDK if making PR to it is a good solution.

**Pull request closed without merging**
